### PR TITLE
fix #14

### LINKED ISSUE #14: Wrong result with `exp!`
I'm using this package to differentiate through `exp!` with ForwardDiff, but I seem to get incorrect results. Below is a MWE that produces a large error. 
```julia
using LinearAlgebra, ForwardDiff, FiniteDiff, ForwardDiffChainRules
@ForwardDiff_frule LinearAlgebra.exp!(x1::AbstractMatrix{<:ForwardDiff.Dual})
function test_exp(x)
    X = copy(reshape(x, 4, 4))
    LinearAlgebra.exp!(X)
    sum(X)
end

x = randn(16)
g1 = ForwardDiff.gradient(test_exp, x)
g2 = FiniteDiff.finite_difference_gradient(test_exp, x)
norm(g1-g2)

julia> norm(g1-g2)
3.7329399053147245
```

The `exp!` rule in ChainRules appears to be extensively tested, so I assume that the error lies here?

### PR DESCRIPTION
**Pull request by baggepinnen**
This PR adds an option to indicate that the function a rule is defined for is mutating its input argument.

Closes #14

### CODE REVIEW

**Comment by ThummeTo** [comment]
Looks good to me @mohamed82008 - Please check if you find the time, I assigned you for review :-)

File: test/runtests.jl [hunk 1]
```diff
@@ -169,6 +171,14 @@ SOFTWARE.
         @test frule_count == 16
         @test norm(g - I) < 1e-6
     end
+    @testset "exp!" begin
+        # Gradient of trace
+        fexp = x -> sum(LinearAlgebra.exp!(copy(x)))
```
Comment (mohdibntarek) [inline test/runtests.jl:173]: Did you mean to use the trace here instead of sum?

Probably also worth testing that the `frule` is being used under the hood. Perhaps use a wrapper function around `exp!` that tests that the element type of the input is not `ForwardDiff.Dual`? You will need to define an `frule` for that function which just calls `exp!`'s `frule`.

Comment (baggepinnen) [reply test/runtests.jl:173]: No, I just wanted a scalar so sum is fine. The rule is called because without it the correctness test fails: #14

Comment (mohdibntarek) [reply test/runtests.jl:173]: I see. The comment above the line of code says `# Gradient of trace` that's why I asked.

File: test/runtests.jl [hunk 2]
```diff
@@ -169,6 +171,14 @@ SOFTWARE.
         @test frule_count == 16
         @test norm(g - I) < 1e-6
     end
+    @testset "exp!" begin
+        # Gradient of trace
```
Comment (mohdibntarek) [inline test/runtests.jl]:
```suggestion
```

File: test/runtests.jl (hunk 1 above)
Comment (mohdibntarek) [reply test/runtests.jl:173]: Does ForwardDiff on its own without this package error or give incorrect gradient?

Comment (baggepinnen) [reply test/runtests.jl:173]: Ah, a copy paste mistake 😅
Without this rule there is no method matching `exp!` for dual matrices, and without the fix in the pr defining that method with this package returns an incorrect answer.

**Comment by mohdibntarek** [comment]
I think the test failures are related to ImplicitDifferentiation 0.4 changing their API using 3 arguments instead of 2. The tests need to be updated but it's not related to this PR.

**Review by mohdibntarek — APPROVED** [review]

**Comment by mohdibntarek** [comment]
bump

**Comment by ThummeTo** [comment]
Sorry for delay, I merged #17 first, so we can see if it's running now.

File: test/runtests.jl
Comment (ThummeTo) [inline test/runtests.jl:1]: Looks like `import FiniteDifferences` is missing?
(test currently fail after mergin #17 )
